categories: [Variant Analysis]
description: Fast and efficient program for estimating individual admixture coefficients
name: snmf
owner: vmarcon
long_description: Fast and efficient program for estimating individual admixture coefficients based on sparse non-negative matrix factorization and population genetics. 
